### ISSUE TITLE
How to handle manual actions?

### ISSUE THREAD

**Issue by davidlivingrooms** [smarkets/marge-bot#195]
My pipeline has a manual action that will kick off more resource intensive jobs like creation of test environments and e2e tests. These should not happen on every commit but only when the developer wants to or when marge is attempting to merge :).

However, I get 
```
2019-05-20 15:33:25,440 WARNING Suspicious CI status: 'manual'
```
and marge never processes the pipeline since it is stuck on manual.

I thought about modifying marge to use the api to trigger the manual action if it is encountered. Perhaps it could be handled by an app argument like `--trigger-manual`

Are there better supported ways to handle this type of workflow with marge-bot? Is this auto-trigger manual option a terrible idea?

**Comment by davidlivingrooms** [comment]
You can use the gitlab `except` directive and check for the marge user. 

```
start_environment:
  stage: start_environment
  tags:
  - linux-docker
  dependencies: []
  when: manual
  allow_failure: false
  except:
    variables:
    - $GITLAB_USER_LOGIN=~ /marge-bot/
```

Works for my use-case . Closing.
