### ISSUE TITLE
Marge-bot logs "Someone skipped the queue! Will have to try again..." even though she merged an MR

### ISSUE THREAD

**Issue by perlun** [smarkets/marge-bot#337]
As noted in the issue title, we are seeing the above log message for scenarios _even when Marge-bot was the one who merged a particular merge request_. This feels a bit silly, but is this expected? :thinking: 

I'm thinking that perhaps logging a message in these MRs saying "Another MR was merged, rebasing and preparing for merge" or something to the like would make more sense. Could this be caused by our local configuration or is it a bug/feature?

Here is our current marge-bot config:

```yaml
rebase-remotely: true
gitlab-url: https://some-git-server
project-regexp: "some-namespace/.*$"
auth-token-file: /configuration/private/auth-token
ssh-key-file: /configuration/private/id_ed25519
merge-order: assigned_at
ci-timeout: 30min
```
